name: Checkpoint 10
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lets Checkout 
        uses: actions/checkout@v7
      
      - name: Lets setup cache
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{runner.os}}-npm-${{hashFiles('**/package-lock.json')}}
          restore-key: ${{runner.os}}-npm-
      
      - run: npm install
      
      - run: echo "build complete" > build-output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-output
          path: build-output.txt
  ajob:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: build-output
        run: cat build-output.txt