name: Environment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment 
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging-approval
    steps:
    - name: Echo
      run: echo "build ran successfully with variable ${{inputs.environment}}"  
